USE ConstructionCompany;
GO

ALTER TABLE Employees ADD  
    ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
        CONSTRAINT DF_Employees_ValidFrom DEFAULT SYSUTCDATETIME(),
    ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
        CONSTRAINT DF_Employees_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
GO

ALTER TABLE Employees  
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.Employees_History));
GO

UPDATE Employees
SET Phone = '0991111111'
WHERE EmployeeID = 1;

UPDATE Employees
SET Phone = '0988888888'
WHERE EmployeeID = 2;

UPDATE Employees
SET Phone = '0993333335'
WHERE EmployeeID = 1;

SELECT * 
FROM Employees FOR SYSTEM_TIME ALL
WHERE EmployeeID = 1
ORDER BY ValidFrom;



ALTER TABLE Projects ADD  
    ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
        CONSTRAINT DF_Projects_ValidFrom DEFAULT SYSUTCDATETIME(),
    ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
        CONSTRAINT DF_Projects_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
GO

ALTER TABLE Projects  
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.Projects_History));
GO

UPDATE Projects
SET StatusID = 2
WHERE ProjectID = 1;

SELECT *
FROM Projects_History
ORDER BY ValidFrom;

SELECT *
FROM Projects
FOR SYSTEM_TIME ALL
WHERE ProjectID = 1;
